name: final-newline-checker

on:
  pull_request:
    # NO paths filter

jobs:
  final-newline-checker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: hakadoriya-actions/final-newline-checker@v0.0.1
        id: final-newline-checker
        with:
          # NOTE: If you want to fail on missing final newline, set this to true
          #fail-on-missing: true
          #paths: |-
          #  ^action.yml
          #  ^missing-final-newline.md
          paths-ignore: |-
            .*\.ico$
            .*\.png$
      - name: Submit PR comment if missing final newline
        if: ${{ steps.final-newline-checker.outputs.missing == 'true' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Create comment body
          cat <<EOF | perl -pe 's/\\n/\n/g' | tee /tmp/gh-pr-comment-body.md
          ## ðŸš¨ Missing final newline

          The following files are missing final newline.

          \`\`\`
          ${{ steps.final-newline-checker.outputs.missing-files }}
          \`\`\`
          EOF
          # Submit PR comment
          gh pr comment ${{ github.event.pull_request.number }} --body-file /tmp/gh-pr-comment-body.md
          # fail the workflow
          exit 1
